// Generated by CoffeeScript 2.3.1
(function() {
  var background, hue_rot, nav_class;

  nav_class = function() {
    var nav;
    nav = document.querySelector('.nav');
    if (window.scrollY === 0 && !nav.classList.contains('top')) {
      return nav.classList.add('top');
    } else if (window.scrollY > 0 && nav.classList.contains('top')) {
      return nav.classList.remove('top');
    }
  };

  hue_rot = 0;

  background = document.querySelector('.background');

  window.addEventListener('scroll', function() {
    nav_class();
    hue_rot = hue_rot + 0.2 % 360;
    return background.style = 'filter: hue-rotate(' + hue_rot + 'deg)';
  });

  window.addEventListener('load', function() {
    var projects;
    nav_class();
    projects = document.querySelectorAll('.projects .project .expandThis');
    return projects.forEach(function(project) {
      return project.classList.add('collapsed');
    });
  });

  (document.querySelectorAll('.projects .project')).forEach(function(project) {
    var toExpand;
    toExpand = project.querySelector('.expandThis');
    toExpand.setAttribute('calc-height', toExpand.offsetHeight);
    return (project.querySelector('h3')).onclick = function() {
      if (toExpand.classList.contains('collapsed')) {
        toExpand.setAttribute('style', 'height: ' + (toExpand.getAttribute('calc-height')) + 'px;');
      } else {
        toExpand.setAttribute('style', '');
      }
      return toExpand.classList.toggle('collapsed');
    };
  });

}).call(this);
